site_name: Control Plane SDK for Python
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_section_style: list
            members_order: source
            show_root_heading: true
            show_source: false
            show_signature_annotations: true
nav:
  # - Home: index.md
  - Client: client.md
theme: readthedocs