site_name: Control Plane SDK for Python
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_section_style: list
            members_order: source
            show_root_heading: true
            show_source: false
            show_signature_annotations: true
nav:
  # - Home: index.md
  - Client: client.md
  - GVCs: gvcs.md
  - Images: images.md
  - Workloads: workloads.md
  - Library API: api.md
  - Tutorial: tutorials/index.md
    # - tutorials/gettingstarted.md
  - Change Log: change-log.md
  # - Contributing: contributing.md
  # - License: license.md
  # - Support: support.md

theme: readthedocs