name: Python package

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Release name'
        required: true
        default: 'v0.0.1'
  push:
    tags:
      - 'release-*'

env:
  # tag_name: ${{ github.event.ref }}
  tag_name: ${{ github.ref_name }}

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.12

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache-dependency-path: pdm.lock

      - name: Install Dependencies
        run: |
          pdm sync -d

      - name: Build package
        run: |
          pdm build

      - name: Create release
        run: |
          tag_name=$(pdm version)
          gh release create "v$tag_name" dist/* \
              --repo="$GITHUB_REPOSITORY" \
              --title="$tag_name" \
              --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}