name: Python package

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Release name'
        required: true
        default: 'v0.0.1'
  push:
    tags:
      - 'release-*'

env:
  # tag_name: ${{ github.event.ref }}
  tag_name: ${{ github.ref_name }}

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.12

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache-dependency-path: pdm.lock

      - name: Install Dependencies
        run: |
          pdm sync -d

      - name: Build package
        run: |
          pdm build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/


  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      id-token: write
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/

      # - name: Create release
      #   run: |
      #     tag_name=$(pdm version)
      #     gh release create "$tag_name" dist/* \
      #         --repo="$GITHUB_REPOSITORY" \
      #         --title="$tag_name" \
      #         --generate-notes
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}