name: Python package

on:
  workflow_dispatch:

  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.12

      - name: Build package
        run: |
          pdm build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/


  pypi-publish:

    runs-on: ubuntu-latest
    needs:
      - build

    permissions:
      id-token: write

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/

      # - name: Create release
      #   if: github.event.action == 'push'
      #   run: |
      #     gh release create "${{ github.ref_name }}" dist/* \
      #         --repo="$GITHUB_REPOSITORY" \
      #         --title="$tag_name" \
      #         --generate-notes
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}

      - name: Upload assets to release
        if: github.event.action == 'published'
        run: |
          gh release upload "${{ github.ref_name }}" dist/* \
              --repo="$GITHUB_REPOSITORY"
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}